<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class App_setting extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('App_setting_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $id =1;
        $row = $this->App_setting_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'app_setting' =>$this->App_setting_model->get_by_id(1),
                'action' => site_url('app_setting/update_action'),
        'id' => set_value('id', $row->id),
        'nama_aplikasi' => set_value('nama_aplikasi', $row->nama_aplikasi),
        'nama_sekolah' => set_value('nama_sekolah', $row->nama_sekolah),
        'alamat_sekolah' => set_value('alamat_sekolah', $row->alamat_sekolah),
        'logo_sekolah' => set_value('logo_sekolah', $row->logo_sekolah),
        'ttd_kepsek' => set_value('ttd_kepsek', $row->ttd_kepsek),
        'author' => set_value('author', $row->author),
        );
            $this->template->load('template','app_setting/app_setting_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('app_setting'));
        }
    }

    
    public function update_action() 
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->index();
        }else {

                $config['upload_path']      = './admin/assets/img/sekolah'; 
                $config['allowed_types']    = 'jpg|png|jpeg'; 
                $config['max_size']         = 10048; 
                $config['file_name']        = 'File-'.date('ymd').'-'.substr(sha1(rand()),0,10); 
                $this->load->library('upload',$config);
                $this->upload->initialize($config);

            //lgoo sekolah
            if ($this->upload->do_upload("logo_sekolah")) 
            {
                

                $id = $this->input->post('id');
                $row = $this->App_setting_model->get_by_id($id);
                $data = $this->upload->data();
                $logo_sekolah =$data['file_name'];
                if($row->logo_sekolah==null || $row->logo_sekolah=='' ){

                }else{
                $target_file = './admin/assets/img/sekolah/'.$row->logo_sekolah;
                unlink($target_file);
                }
            }else{
                $logo_sekolah = $this->input->post('logo_sekolah_lama');
            }

            // ttd_kepsek
            if ($this->upload->do_upload("ttd_kepsek")) 
            {

                    $id = $this->input->post('id');
                    $row = $this->App_setting_model->get_by_id($id);
                    $data2 = $this->upload->data();
                    $ttd_kepsek =$data2['file_name'];
                    if($row->ttd_kepsek==null || $row->ttd_kepsek=='' ){

                    }else{
                    $target_file = './admin/assets/img/sekolah/'.$row->ttd_kepsek;
                    unlink($target_file);
                    }
            }else{
                $ttd_kepsek = $this->input->post('ttd_kepsek_lama');
            }



            $data = array(
        		'nama_aplikasi' => $this->input->post('nama_aplikasi',TRUE),
        		'nama_sekolah' => $this->input->post('nama_sekolah',TRUE),
        		'alamat_sekolah' => $this->input->post('alamat_sekolah',TRUE),
        		'logo_sekolah' => $logo_sekolah,
                'ttd_kepsek' => $ttd_kepsek,
        		'author' => $this->input->post('author',TRUE),
	           );

            $this->App_setting_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('app_setting'));
        }
    }
    

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_aplikasi', 'nama aplikasi', 'trim|required');
	$this->form_validation->set_rules('nama_sekolah', 'nama sekolah', 'trim|required');
	$this->form_validation->set_rules('alamat_sekolah', 'alamat sekolah', 'trim|required');
	$this->form_validation->set_rules('author', 'author', 'trim|required');
	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file App_setting.php */
/* Location: ./application/controllers/App_setting.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-01 10:11:15 */
/* http://harviacode.com */