<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'siswa';
    public $id = 'siswa_id';
    public $order = 'DESC';
    public $akses = [];

    function __construct()
    {
        parent::__construct();
        if ($this->session->userdata()['level'] == '2') {
            $this->db->where('akses_kelas_walikelas.user_id = ' . $this->session->userdata()['userid']);
            $this->akses = $this->db->get('akses_kelas_walikelas')->result();
        } else if ($this->session->userdata()['level'] == '3') {
            $this->db->where('akses_kelas_guru.user_id = ' . $this->session->userdata()['userid']);
            $this->akses = $this->db->get('akses_kelas_guru')->result();
        } else if ($this->session->userdata()['level'] == '4') {
            echo "Anda tidak punya akses!";
            die;
        }
    }

    // get all
    function get_all($kelas_id = null)
    {
        if ($kelas_id != null) {
            $this->db->where($this->table . '.kelas_id = ' . $kelas_id);
        } else {
            // hak akses
            if ($this->session->userdata()['level'] != '1') {
                foreach ($this->akses as $o) {
                    $this->db->where($this->table . '.kelas_id = ' . $o->kelas_id);
                }
            }
            // end hak akses
        }
        $this->db->join('kelas', 'siswa.kelas_id = kelas.kelas_id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('user', 'user.user_id = siswa.user_id', 'left');
        $this->db->join('kelas', 'siswa.kelas_id = kelas.kelas_id', 'left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        // hak akses
        foreach ($this->akses as $o) {
            $this->db->where($this->table . '.kelas_id = ' . $o->kelas_id);
        }
        // end hak akses
        $this->db->group_start();
        $this->db->like('siswa_id', $q);
        $this->db->or_like('nama_siswa', $q);
        $this->db->or_like('jenis_kelamin', $q);
        $this->db->or_like('kelas_id', $q);
        $this->db->or_like('nama_ibu', $q);
        $this->db->or_like('nama_ayah', $q);
        $this->db->or_like('no_hp_wali_murid', $q);
        $this->db->group_end();
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        // hak akses
        foreach ($this->akses as $o) {
            $this->db->where($this->table . '.kelas_id = ' . $o->kelas_id);
        }
        // end hak akses
        $this->db->join('user', 'user.user_id = siswa.user_id', 'left');
        $this->db->join('kelas', 'siswa.kelas_id = kelas.kelas_id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->group_start();
        $this->db->like('siswa_id', $q);
        $this->db->or_like('nama_siswa', $q);
        $this->db->or_like('jenis_kelamin', $q);
        $this->db->or_like('kelas.nama_kelas', $q);
        $this->db->or_like('nama_ibu', $q);
        $this->db->or_like('nama_ayah', $q);
        $this->db->or_like('no_hp_wali_murid', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-23 13:31:08 */
/* http://harviacode.com */